# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/andreyvit/diff"
